### ISSUE TITLE
Kotlin Multiplatform Support

### ISSUE THREAD

**Issue by charlee-dev** [Hukumister/LazyCardStack#3]
Hi. I use your project in the Kotlin Multiplatform project Android, iOS and Desktop, but it will support WASM, too. Would you like me to create a PR for your repo to enable KMP support? Ofc you will need to update your Maven publish pipeline to publish KMP artefacts.

**Comment by Hukumister** [comment]
Hi, of course I’d like you to create PR,  I’ll update maven publish settings after it
