### ISSUE TITLE
index is not saving after modifying a list

### ISSUE THREAD

**Issue by oleginvoke** [Hukumister/LazyCardStack#7]
I have a list item with "selected" field.
After modifying a list like this:
list.map { item -> if(needToSelect) item.copy(selected = true) else item }
current index of card is reset, but I want to modify only selected item.

**Comment by Hukumister** [comment]
@olegaches could you please write the code of the UI part, what do you use for key items when you try to show stack?

**Comment by oleginvoke** [comment]
Never mind, it was my mistake, there was an effect triggering 'cardStackState.snapTo(0)', sorry
